# Решение СЛАУ

Будем решать систему линейных уравнений методом Крамера.  Если определитель системы отличен от нуля, то система линейных уравнений имеет одно единственное решение, причём неизвестное равно отношению определителей. В знаменателе – определитель системы, а в числителе – определитель, полученный из определителя системы путём замены коэффициентов при этом неизвестном свободными членами.

### Условия применимости:

Метод Крамера может быть использован в решении системы стольких линейных уравнений, сколько в каждом уравнении неизвестных. Если определитель системы не равен нулю, то метод Крамера может быть использован в решении, если же равен нулю, то не может. Кроме того, метод Крамера может быть использован в решении систем линейных уравнений, имеющих единственное решение.

In [1]:
from __future__ import division

In [2]:
import numpy as np

In [3]:
def det(matrix, mul):
    mat = matrix[:]
    width = len(mat)
    if width == 1:
        return mul * mat[0][0]
    else:
        sign = -1
        result = 0
        for i in range(width):
            m = []
            for j in range(1, width):
                buff = []
                for k in range(width):
                    if k != i:
                        buff.append(mat[j][k])
                m.append(buff)
            sign *= -1
            result += mul * det(m, sign * mat[0][i])
    return result
 
def kramer(m, b):
    tmp = list(zip(*m))
    delta = det(tmp, 1)
    if delta == 0:
        return "Решений нет"
    result = []
    for i in range(len(m)):
        A = tmp[:]
        A[i] = b
        result.append((det(A, 1) / delta)[0])
    return np.array(result)

Найдем решение уравнения $Ax=b$, если 
$$
\begin{equation}
    A = \begin{pmatrix}
        1 & 2 & 3 \\
        2.001 & 3.999 & 6 \\         
        15 & 3 & 6
        \end{pmatrix} \quad
    b = \begin{pmatrix}
            1 \\
            2\\         
            3
        \end{pmatrix}
\end{equation}
$$


In [4]:
matrix = np.array([[1,2,3],
                  [2.001, 3.999, 6],
                  [15, 3, 6]])
b = np.array([1, 2, 3]).reshape(-1,1)
A = matrix

x = kramer(matrix, b).reshape(-1, 1)
print("x = \n")
print(x)
print("\nНевязка \n")
print(abs(b - np.dot(A, x)))

x = 

[[ 0.08333333]
 [ 0.08333333]
 [ 0.25      ]]

Невязка 

[[  3.94795308e-13]
 [  7.89590615e-13]
 [  1.18394183e-12]]


Найдем решение уравнения $Ax=b$, если 
$$
\begin{equation}
    A = \begin{pmatrix}
        1 & \frac{1}{2} & \frac{1}{3} \\
        \frac{1}{2} & \frac{1}{3} & \frac{1}{4} \\         
        \frac{1}{3} & \frac{1}{4} & \frac{1}{5}
        \end{pmatrix} \quad
    b = \begin{pmatrix}
            1 \\
            2\\         
            3
        \end{pmatrix}
\end{equation}
$$


In [5]:
matrix = np.array([[1,1/2,1/3],
                   [1/2, 1/3, 1/4],
                   [1/3, 1/4, 1/5]])
b = np.array([1, 2, 3]).reshape(-1,1)
A = matrix
x = kramer(matrix, b).reshape(-1,1)
print("x = \n")
print(x)
print("\nНевязка \n")
print(abs(b - np.dot(A, x)))

x = 

[[  27.]
 [-192.]
 [ 210.]]

Невязка 

[[  2.84217094e-14]
 [  4.26325641e-14]
 [  5.68434189e-14]]


Найдем решение уравнения $Ax=b$, если 
$$
\begin{equation}
    A = \begin{pmatrix}
        10^{6} & 2 \\        
        10^{13} & 2
        \end{pmatrix} \quad
    b = \begin{pmatrix}
            2 \\
            1        
        \end{pmatrix}
\end{equation}
$$

In [8]:
matrix = np.array([[10**6,2],
                   [10**13, 2]])
b = np.array([2, 1]).reshape(-1,1)
A = matrix
x = kramer(matrix, b).reshape(-1, 1)
print("x = \n")
print(x)
print("\nНевязка \n")
print(abs(b - np.dot(A, x)))

x = 

[[ -1.00000010e-13]
 [  1.00000005e+00]]

Невязка 

[[ 0.]
 [ 0.]]
